const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const screens=$$('.screen'); const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');
const bg=new Image();bg.src='assets/MetroCity.png';
const save=JSON.parse(localStorage.getItem('flapverse-save')||'{"best":0,"coins":368,"world":1,"bird":0}');
let state='home', running=false, paused=false, last=0, raf, W=0,H=0,dpr=1;
let bird, obstacles=[], particles=[], score=0,runCoins=0,combo=0,distance=0,speed=340,spawnIn=0;
function persist(){localStorage.setItem('flapverse-save',JSON.stringify(save));$$('[data-coins]').forEach(x=>x.textContent=save.coins.toLocaleString())}persist();
function show(id){screens.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');state=id;if(id==='home')updateHomeWorld();else homeVideo?.pause()}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function reset(){score=runCoins=combo=distance=0;speed=Math.max(330,W*.2);spawnIn=1;obstacles=[];particles=[];bird={x:W*.32,y:H*.48,vy:0,lane:1,targetX:W*.32,rot:0,alive:true};updateHud()}
function start(){show('game');resize();reset();running=true;paused=false;last=performance.now();$('#paused').classList.add('hidden');$('#hint').style.opacity=1;setTimeout(()=>$('#hint').style.opacity=0,2600);cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function flap(){if(!running||paused)return;bird.vy=-(H*.35);burst(bird.x-25,bird.y+15,'#42dfff',7)}
function lane(dir){if(!running||paused)return;bird.lane=Math.max(0,Math.min(2,bird.lane+dir));bird.targetX=W*(.27+bird.lane*.055);burst(bird.x,bird.y,'#dd4dff',4)}
let touch=null;canvas.addEventListener('pointerdown',e=>touch={x:e.clientX,y:e.clientY,t:performance.now()});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))lane(dx>0?1:-1);else flap();touch=null});
addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp')flap();if(e.code==='ArrowLeft')lane(-1);if(e.code==='ArrowRight')lane(1)});
function spawn(){const gap=H*(.29-Math.min(.07,score/8000));const center=H*(.28+Math.random()*.44);const w=Math.max(75,W*.055);obstacles.push({x:W+w,y:center,gap,w,scored:false,coin:Math.random()>.25,phase:Math.random()*6.3});spawnIn=Math.max(.95,1.7-score/4500)}
function burst(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:-80-Math.random()*180,vy:(Math.random()-.5)*140,a:1,r:2+Math.random()*4,color})}
function update(dt){distance+=speed*dt*.018;speed+=dt*2;bird.vy+=H*1.155*dt;bird.y+=bird.vy*dt;bird.x+=(bird.targetX-bird.x)*Math.min(1,dt*10);bird.rot=Math.max(-.45,Math.min(.85,bird.vy/550));spawnIn-=dt;if(spawnIn<=0)spawn();
  obstacles.forEach(o=>{o.x-=speed*dt;o.phase+=dt;const top=o.y-o.gap/2,bottom=o.y+o.gap/2;if(!o.scored&&o.x+o.w<bird.x){o.scored=true;score+=100+combo*10;combo++;if(o.coin){runCoins++;burst(o.x+o.w/2,o.y,'#ffd32c',10)}pulse()}
    const bx=bird.x,by=bird.y,r=14;if(bx+r>o.x&&bx-r<o.x+o.w&&(by-r<top||by+r>bottom))die();});obstacles=obstacles.filter(o=>o.x>-150);
  particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.a-=dt*1.8});particles=particles.filter(p=>p.a>0);if(bird.y<25||bird.y>H-25)die();updateHud();if(Math.floor(distance)%500<5)$('#bossWarning').classList.toggle('show',distance>100)}
function pulse(){const c=$('#combo');c.classList.add('pulse');setTimeout(()=>c.classList.remove('pulse'),160)}
function updateHud(){$('#score').textContent=score.toLocaleString();$('#best').textContent=save.best.toLocaleString();$('#runCoins').textContent=runCoins;$('#distance').textContent=Math.floor(distance)+'m';$('#combo b').textContent=combo}
function die(){if(!running)return;running=false;save.coins+=runCoins;const isBest=score>save.best;if(isBest)save.best=score;persist();$('#finalScore').textContent=score.toLocaleString();$('#rewardCoins').textContent=runCoins;$('#rewardGems').textContent=Math.floor(runCoins/10);$('#newBest').style.visibility=isBest?'visible':'hidden';$('#adBtn').disabled=false;$('#adBtn').classList.remove('claimed');setTimeout(()=>show('gameover'),450)}
function loop(t){if(!running)return;const dt=Math.min(.032,(t-last)/1000);last=t;if(!paused)update(dt);draw(t/1000);raf=requestAnimationFrame(loop)}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(t){ctx.clearRect(0,0,W,H);if(bg.complete)ctx.drawImage(bg,0,0,W,H);ctx.fillStyle='rgba(5,15,49,.1)';ctx.fillRect(0,0,W,H);
  for(let i=0;i<8;i++){const x=((W-i*260-(t*speed*.05))%(W+300)+W+300)%(W+300)-100;ctx.fillStyle='#ffffff33';ctx.beginPath();ctx.arc(x,H*.15+(i%3)*H*.22,2+i%2,0,7);ctx.fill()}
  obstacles.forEach(o=>drawPillar(o));particles.forEach(p=>{ctx.globalAlpha=p.a;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r*2,p.r*2)});ctx.globalAlpha=1;drawBird(t)}
function drawPillar(o){const top=o.y-o.gap/2,bottom=o.y+o.gap/2,w=o.w;const grad=ctx.createLinearGradient(o.x,0,o.x+w,0);grad.addColorStop(0,'#08152c');grad.addColorStop(.45,'#173e72');grad.addColorStop(.7,'#07152e');grad.addColorStop(1,'#020817');ctx.fillStyle=grad;ctx.shadowColor='#16bfff';ctx.shadowBlur=12;roundRect(o.x,-25,w,top+25,13);ctx.fill();roundRect(o.x,bottom,w,H-bottom+25,13);ctx.fill();ctx.shadowColor='#f330ff';ctx.shadowBlur=18;ctx.fillStyle='#ec3bff';ctx.fillRect(o.x-7,top-13,w+14,13);ctx.fillRect(o.x-7,bottom,w+14,13);ctx.shadowColor='#25deff';ctx.fillStyle='#21dfff';ctx.fillRect(o.x+10,top-28,w-20,8);ctx.fillRect(o.x+10,bottom+15,w-20,8);ctx.shadowBlur=0;if(o.coin&&!o.scored){ctx.save();ctx.translate(o.x+w/2,o.y);ctx.scale(.65+.2*Math.sin(o.phase),1);ctx.fillStyle='#ffd036';ctx.strokeStyle='#fff19a';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,18,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#ed9412';ctx.font='bold 20px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('★',0,1);ctx.restore()}}
function drawBird(t){ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rot);ctx.scale(.5,.5);ctx.shadowColor='#25e4ff';ctx.shadowBlur=22;ctx.fillStyle='#159be9';ctx.beginPath();ctx.ellipse(0,0,43,32,0,0,7);ctx.fill();ctx.fillStyle='#0b62c1';ctx.beginPath();ctx.ellipse(-25,8,29,13,-.35,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(21,-9,15,18,0,0,7);ctx.fill();ctx.fillStyle='#07162f';ctx.beginPath();ctx.arc(27,-9,6,0,7);ctx.fill();ctx.fillStyle='#ff9f00';ctx.beginPath();ctx.moveTo(40,-2);ctx.lineTo(61,6);ctx.lineTo(40,13);ctx.fill();ctx.fillStyle='#39d7ff';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(-10+i*10,-31-i%2*4,8,15,-.4+i*.25,0,7);ctx.fill()}ctx.restore()}

const worldData=[['world-forest','MYSTIC FOREST','8,742'],['world-metro','METRO CITY','15,630'],['world-space','SPACE ODYSSEY','23,918'],['world-cyber','CYBER CITY','LOCKED'],['world-ocean','OCEAN REALM','LOCKED']];
const homeWorlds=[
  {name:'MYSTIC FOREST',video:'assets/MysticForest-pingpong.mp4',poster:'assets/MysticForest-poster.jpg'},
  {name:'METRO CITY',video:'assets/MetroCity-pingpong.mp4',poster:'assets/MetroCity-poster.jpg'},
  {name:'SPACE ODYSSEY',video:'assets/SpaceOdyssey-pingpong.mp4',poster:'assets/SpaceOdyssey-poster.jpg'}
];
const characterData=[['character-bird','NEON BIRD','EPIC'],['character-ember','EMBER','LEGENDARY'],['character-byte','BYTE','RARE'],['character-nox','NOX','EPIC'],['character-ufo','UFO','RARE'],['character-rocket','ROCKET','LEGENDARY']];
const homeVideo=$('#homeBackground');
function updateHomeWorld(){
  const selected=homeWorlds[Math.min(save.world,homeWorlds.length-1)]||homeWorlds[1];
  $('#homeWorldName').textContent=selected.name;
  if(homeVideo.dataset.src!==selected.video){
    homeVideo.dataset.src=selected.video;
    homeVideo.poster=selected.poster;
    homeVideo.src=selected.video;
    homeVideo.load();
  }
  homeVideo.play().catch(()=>{});
}
homeVideo.addEventListener('loadeddata',()=>homeVideo.classList.add('ready'));
homeVideo.addEventListener('waiting',()=>homeVideo.classList.remove('ready'));
const menus={
 worlds:{title:'WORLD SELECT',html:()=>`<div class="world-layout"><div class="world-cards">${worldData.map((x,i)=>`<button class="world-card ${save.world===i?'selected':''} ${i>2?'locked':''}" data-world="${i}"><span class="world-number">${i+1}</span><span class="world-art ${x[0]}"></span><b>${x[1]}</b><small>${i>2?'🔒 LOCKED':'BEST SCORE'}</small><em>${x[2]}</em></button>`).join('')}</div><div class="total-progress"><b>TOTAL PROGRESS</b><span>⭐ 9 / 25</span><progress value="9" max="25"></progress><i>🎁</i></div></div>`},
 characters:{title:'CHARACTER SELECT',html:()=>{const c=characterData[save.bird]||characterData[0];return `<div class="character-layout"><div class="character-stage"><div class="character-glow"></div><span id="characterHero" class="atlas-character ${c[0]}"></span></div><div class="character-info"><h2 id="characterName">${c[1]}</h2><label id="characterRarity">${c[2]}</label><div class="stat"><b>Speed</b><i><span style="width:72%"></span></i></div><div class="stat boost"><b>Boost</b><i><span style="width:68%"></span></i></div><div class="stat control"><b>Control</b><i><span style="width:78%"></span></i></div><button class="selected-button">SELECTED ✓</button></div><div class="character-strip">${characterData.map((x,i)=>`<button data-character="${i}" class="character-thumb ${save.bird===i?'selected':''}"><span class="atlas-character ${x[0]}"></span><small>${x[1]}</small></button>`).join('')}</div></div>`}},
 missions:{title:'MISSIONS',html:()=>`<div class="mission-shell"><div class="mission-tabs"><button class="active">DAILY <i>3</i></button><button>WEEKLY</button><span>◷ Resets in: 14h 35m</span></div><div class="mission-list">${[['🪽','Fly 1,000 meters',65,'650 / 1,000','🪙 200'],['⭐','Collect 200 coins',60,'120 / 200','💎 10'],['⚡','Get 10 Perfect Passes',60,'6 / 10','⚡ 5'],['🌀','Enter 3 Portals',33,'1 / 3','🪙 300']].map(x=>`<div class="mission-row"><span class="mission-icon">${x[0]}</span><div><b>${x[1]}</b><progress value="${x[2]}" max="100"></progress><small>${x[3]}</small></div><strong>${x[4]}</strong><button class="mission-go">GO</button></div>`).join('')}</div><div class="mission-bonus">Complete all daily missions to get bonus reward! <span>🎁</span></div></div>`},
 shop:{title:'SHOP',html:()=>`<div class="shop-shell"><nav class="shop-tabs">${['⭐ Featured','👤 Characters','🧩 Skins','🌈 Trails','⚡ Power-ups','🪙 Coins & Gems'].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('')}</nav><div class="shop-content"><div class="offer-row"><article class="offer-card"><i>-50%</i><h3>SPECIAL OFFER</h3><span>🎁</span><b>10,000 🪙 + 500 💎</b><button>₹249.00</button></article><article class="offer-card"><i>BEST VALUE</i><h3>STARTER PACK</h3><span>⚡</span><b>Boost · Gems · Energy</b><button>₹499.00</button></article></div><h3>COIN PACKS</h3><div class="coin-packs">${[['🪙','2,000','₹99'],['💰','5,000','₹199'],['🎁','12,000','₹399'],['🧰','25,000','₹799']].map(x=>`<button><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></div></div>`},
 leaderboard:{title:'LEADERBOARD',html:()=>`<div class="list">${['NovaPilot|45,820','SkyRider|38,450','PlayerOne|25,630','ByteWing|22,190','CloudAce|18,775'].map((x,i)=>{let[a,b]=x.split('|');return `<div class="row"><b>#${i+1}</b><span class="grow">${a}</span><b>${b}</b></div>`}).join('')}</div>`},
 settings:{title:'SETTINGS',html:()=>`<div class="list panel"><div class="setting"><b>Music</b><button class="toggle">ON</button></div><div class="setting"><b>Sound effects</b><button class="toggle">ON</button></div><div class="setting"><b>Haptics</b><button class="toggle">ON</button></div><div class="setting"><b>Control hints</b><button class="toggle">ON</button></div></div>`}
};
function openMenu(name){const m=menus[name];if(!m)return;$('#panelTitle').textContent=m.title;$('#panelCurrency').innerHTML=name==='characters'?`<span class="panel currency-pill">💎 <b>320</b><button>+</button></span>`:name==='missions'||name==='settings'||name==='leaderboard'?'':`<span class="panel currency-pill">🪙 <b data-coins>${save.coins.toLocaleString()}</b><button>+</button></span>${name==='shop'?'<span class="panel currency-pill">💎 <b>320</b><button>+</button></span>':''}`;$('#panelContent').innerHTML=m.html();show('panelScreen');bindPanel(name)}
function bindPanel(name){$$('.toggle').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='ON'?'OFF':'ON';b.classList.toggle('toggle')});$$('[data-world]').forEach(b=>b.onclick=()=>{const i=+b.dataset.world;if(i>2)return;save.world=i;persist();openMenu('worlds')});$$('[data-character]').forEach(b=>b.onclick=()=>{save.bird=+b.dataset.character;persist();openMenu('characters')});$$('.mission-go').forEach(b=>b.onclick=()=>start());}
$$('[data-open]').forEach(b=>b.onclick=()=>openMenu(b.dataset.open));$('.back').onclick=()=>show('home');$$('[data-home]').forEach(b=>b.onclick=()=>{running=false;show('home')});$('#playBtn').onclick=start;$('#retryBtn').onclick=start;$('#adBtn').onclick=()=>{if($('#adBtn').disabled)return;save.coins+=runCoins;persist();$('#rewardCoins').textContent=runCoins*2;$('#adBtn').disabled=true;$('#adBtn').classList.add('claimed');$('#adBtn').innerHTML='✓ REWARD DOUBLED'};$('#pauseBtn').onclick=()=>{paused=true;$('#paused').classList.remove('hidden')};$('#resumeBtn').onclick=()=>{paused=false;last=performance.now();$('#paused').classList.add('hidden')};
document.addEventListener('visibilitychange',()=>{if(document.hidden){homeVideo.pause();if(running){paused=true;$('#paused').classList.remove('hidden')}}else if(state==='home'){homeVideo.play().catch(()=>{})}});updateHomeWorld();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
