const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');
const defaults={best:0,coins:368,gems:320,world:1,bird:0,bestByWorld:[0,0,0,0,0],settings:{music:true,sfx:true,haptics:true,hints:true},missions:{distance:0,coins:0,perfect:0,portals:0,claimed:[],bonusClaimed:false},ownedCharacters:[0],purchases:[],dailyClaimed:''};
let stored={};try{stored=JSON.parse(localStorage.getItem('flapverse-save')||'{}')}catch{}
const save={...defaults,...stored,settings:{...defaults.settings,...stored.settings},missions:{...defaults.missions,...stored.missions}};
for(const key of ['bestByWorld','ownedCharacters','purchases'])if(!Array.isArray(save[key]))save[key]=defaults[key];if(!Array.isArray(save.missions.claimed))save.missions.claimed=[];
if(!save.ownedCharacters.includes(save.bird))save.bird=0;
const worlds=[
 {css:'world-forest',name:'MYSTIC FOREST',video:'assets/MysticForest-pingpong.mp4',poster:'assets/MysticForest-poster.jpg',game:'assets/MtsticForest.png',unlock:0,music:'assets/MtsticForest.mp4'},
 {css:'world-metro',name:'METRO CITY',video:'assets/MetroCity-pingpong.mp4',poster:'assets/MetroCity-poster.jpg',game:'assets/MetroCity.png',unlock:0,music:'assets/MetroCity.mp4'},
 {css:'world-space',name:'SPACE ODYSSEY',video:'assets/SpaceOdyssey-pingpong.mp4',poster:'assets/SpaceOdyssey-poster.jpg',game:'assets/SpaceOdyssey-poster.jpg',unlock:0,music:'assets/SpaceOdyssey.mp4'},
 {css:'world-cyber',name:'CYBER CITY',poster:'assets/MetroCity-poster.jpg',game:'assets/MetroCity.png',unlock:12000,music:'assets/MetroCity.mp4'},
 {css:'world-ocean',name:'OCEAN REALM',poster:'assets/MysticForest-poster.jpg',game:'assets/MtsticForest.png',unlock:25000,music:'assets/MtsticForest.mp4'}];
const characters=[
 {css:'character-bird',name:'NEON BIRD',rarity:'EPIC',asset:'assets/neon-bird-cutout.png',speed:72,boost:68,control:78},
 {css:'character-ember',name:'EMBER',rarity:'LEGENDARY',asset:'assets/Ember.png',speed:84,boost:82,control:62},
 {css:'character-byte',name:'BYTE',rarity:'RARE',asset:'assets/Byte.png',speed:65,boost:58,control:92},
 {css:'character-nox',name:'NOX',rarity:'EPIC',asset:'assets/Nox.png',speed:76,boost:88,control:70},
 {css:'character-ufo',name:'UFO',rarity:'RARE',asset:'assets/UFO.png',speed:88,boost:65,control:74},
 {css:'character-rocket',name:'ROCKET',rarity:'LEGENDARY',asset:'assets/Rocket.png',speed:96,boost:92,control:55}];
const missionDefs=[['distance','🪽','Fly 1,000 meters',1000,200,'coins'],['coins','⭐','Collect 200 coins',200,10,'gems'],['perfect','⚡','Get 10 Perfect Passes',10,5,'gems'],['portals','🌀','Enter 3 Portals',3,300,'coins']].map(([key,icon,label,goal,reward,type])=>({key,icon,label,goal,reward,type}));
const shopItems=[['ember-pass','🐉','UNLOCK EMBER',120,'gems',1,1],['byte-pass','🤖','UNLOCK BYTE',900,'coins',1,2],['nox-pass','🦇','UNLOCK NOX',110,'gems',1,3],['ufo-pass','🛸','UNLOCK UFO',1000,'coins',1,4],['rocket-pass','🚀','UNLOCK ROCKET',180,'gems',1,5],['nova-skin','✨','NOVA SKIN',140,'gems',2],['midnight-skin','🌙','MIDNIGHT SKIN',750,'coins',2],['trail-cyan','🌈','CYAN TRAIL',450,'coins',3],['comet-trail','☄️','COMET TRAIL',95,'gems',3],['shield','🛡️','START SHIELD',80,'gems',4],['coin-boost','⚡','COIN BOOST',650,'coins',4]].map(([id,icon,name,cost,type,tab,character])=>({id,icon,name,cost,type,tab,character}));
let activeShopTab=0;
const homeVideo=$('#homeBackground'),homeMusic=new Audio(),bg=new Image(),birdSprite=new Image();homeMusic.loop=true;homeMusic.volume=.2;
let state='home',toastTimer,audioCtx;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function haptic(pattern=18){if(save.settings.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
function sound(f=520,d=.06){if(!save.settings.sfx)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function persist(){localStorage.setItem('flapverse-save',JSON.stringify(save));$$('[data-coins]').forEach(e=>e.textContent=save.coins.toLocaleString());$$('[data-gems]').forEach(e=>e.textContent=save.gems.toLocaleString())}
function worldUnlocked(i){return i<3||save.best>=worlds[i].unlock}
function applyMusic(){if(save.settings.music&&state==='home')homeMusic.play().catch(()=>{});else homeMusic.pause()}
function updateHomeWorld(){const w=worlds[save.world]||worlds[1];$('#homeWorldName').textContent=w.name;if(w.video&&homeVideo.dataset.src!==w.video){homeVideo.dataset.src=w.video;homeVideo.poster=w.poster;homeVideo.src=w.video;homeVideo.load()}homeVideo.play().catch(()=>{});if(homeMusic.dataset.src!==w.music){homeMusic.dataset.src=w.music;homeMusic.src=w.music;homeMusic.load()}applyMusic();const claimed=save.dailyClaimed===new Date().toISOString().slice(0,10),daily=$('[data-daily]');daily.classList.toggle('claimed',claimed);daily.querySelector('small').textContent=claimed?'Claimed today':'Tap to claim';daily.querySelector('.notification').hidden=claimed;$('.home-avatar').style.backgroundImage=`url('${characters[save.bird].asset}')`}
function show(id){screens.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');state=id;if(id==='home')updateHomeWorld();else{homeVideo.pause();homeMusic.pause()}if(id==='panelScreen'||id==='gameover')$('#'+id).style.backgroundImage=`linear-gradient(#02081799,#020817dd),url('${worlds[save.world].poster}')`}

let running=false,paused=false,last=0,raf,W=0,H=0,dpr=1,bird,obstacles=[],particles=[],score=0,runCoins=0,combo=0,maxCombo=0,distance=0,speed=340,spawnIn=0,grace=0,portalMark=0,shieldActive=false;
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function reset(){const c=characters[save.bird];score=runCoins=combo=maxCombo=distance=portalMark=0;speed=Math.max(300,W*.18)*(c.speed/72);spawnIn=1.6;grace=1.25;shieldActive=save.purchases.includes('shield');obstacles=[];particles=[];bird={x:W*.305,y:H*.48,vy:0,lane:1,targetX:W*.305,rot:0};bg.src=worlds[save.world].game;birdSprite.src=c.asset;updateHud();$('#combo em').classList.remove('visible')}
function start(){show('game');resize();reset();running=true;paused=false;last=performance.now();$('#paused').classList.add('hidden');const ready=$('#readyCountdown');ready.textContent='READY';ready.classList.add('show');setTimeout(()=>ready.textContent='GO!',650);setTimeout(()=>ready.classList.remove('show'),1250);$('#hint').style.opacity=save.settings.hints?1:0;if(save.settings.hints)setTimeout(()=>$('#hint').style.opacity=0,3200);cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);haptic(25);sound(420,.1)}
function flap(){if(!running||paused)return;const c=characters[save.bird];bird.vy=-(H*(.31+c.boost/500));burst(bird.x-25,bird.y+15,save.purchases.includes('trail-cyan')?'#63f5ff':'#42dfff',7);haptic();sound(620)}
function lane(dir){if(!running||paused)return;const c=characters[save.bird];bird.lane=Math.max(0,Math.min(2,bird.lane+dir));bird.targetX=W*(.255+bird.lane*(.045+c.control/5000));burst(bird.x,bird.y,'#dd4dff',4);haptic(12)}
let touch=null;canvas.addEventListener('pointerdown',e=>touch={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))lane(dx>0?1:-1);else flap();touch=null});addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp')flap();if(e.code==='ArrowLeft')lane(-1);if(e.code==='ArrowRight')lane(1)});
function spawn(){const gap=H*(.32-Math.min(.065,score/9000)),center=H*(.3+Math.random()*.4),w=Math.max(70,W*.05);obstacles.push({x:W+w,y:center,gap,w,scored:false,coin:Math.random()>.25,phase:Math.random()*6.3});spawnIn=Math.max(1.05,1.75-score/5000)}
function burst(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:-80-Math.random()*180,vy:(Math.random()-.5)*140,a:1,r:2+Math.random()*4,color})}
function update(dt){if(grace>0){grace-=dt;bird.y=H*.48+Math.sin(performance.now()/180)*4;return}distance+=speed*dt*.018;speed+=dt*1.5;bird.vy+=H*1.08*dt;bird.y+=bird.vy*dt;bird.x+=(bird.targetX-bird.x)*Math.min(1,dt*10);bird.rot=Math.max(-.45,Math.min(.8,bird.vy/600));spawnIn-=dt;if(spawnIn<=0)spawn();obstacles.forEach(o=>{o.x-=speed*dt;o.phase+=dt;const top=o.y-o.gap/2,bottom=o.y+o.gap/2;if(!o.scored&&o.x+o.w<bird.x){o.scored=true;score+=100+combo*10;combo++;maxCombo=Math.max(maxCombo,combo);if(o.coin){runCoins+=save.purchases.includes('coin-boost')?2:1;burst(o.x+o.w/2,o.y,'#ffd32c',10)}pulse()}const r=22;if(!o.hit&&bird.x+r>o.x&&bird.x-r<o.x+o.w&&(bird.y-r<top||bird.y+r>bottom)){if(shieldActive){shieldActive=false;o.hit=true;burst(bird.x,bird.y,'#7ff8ff',24);toast('Shield absorbed the impact');haptic([30,30,50])}else die()}});obstacles=obstacles.filter(o=>o.x>-150);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.a-=dt*1.8});particles=particles.filter(p=>p.a>0);const portal=Math.floor(distance/500);if(portal>portalMark){portalMark=portal;$('#bossWarning').classList.add('show');setTimeout(()=>$('#bossWarning').classList.remove('show'),1400)}if(bird.y<25||bird.y>H-25)die();updateHud()}
function pulse(){const c=$('#combo');c.classList.add('pulse');$('#combo em').classList.toggle('visible',combo>0);setTimeout(()=>c.classList.remove('pulse'),160);sound(760,.05)}
function updateHud(){$('#score').textContent=score.toLocaleString();$('#best').textContent=save.best.toLocaleString();$('#runCoins').textContent=runCoins;$('#distance').textContent=Math.floor(distance)+'m';$('#combo b').textContent=combo}
function die(){if(!running)return;running=false;const travelled=Math.floor(distance);save.coins+=runCoins;save.missions.distance+=travelled;save.missions.coins+=runCoins;save.missions.perfect+=maxCombo;save.missions.portals+=portalMark;const isBest=score>save.best;if(isBest)save.best=score;save.bestByWorld[save.world]=Math.max(save.bestByWorld[save.world]||0,score);persist();$('#finalScore').textContent=score.toLocaleString();$('#rewardCoins').textContent=runCoins;$('#rewardGems').textContent=Math.floor(runCoins/10);$('#newBest').style.visibility=isBest?'visible':'hidden';$('#adBtn').disabled=runCoins===0;$('#adBtn').classList.remove('claimed');setTimeout(()=>show('gameover'),350);haptic([60,40,100]);sound(170,.2)}
function loop(t){if(!running)return;const dt=Math.min(.032,(t-last)/1000);last=t;if(!paused)update(dt);draw();raf=requestAnimationFrame(loop)}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();ctx.filter='blur(3px) brightness(.58) saturate(.78)';if(bg.complete)ctx.drawImage(bg,-8,-8,W+16,H+16);ctx.restore();const lanes=[W*.255,W*.305,W*.355];ctx.save();ctx.setLineDash([5,18]);ctx.lineWidth=2;lanes.forEach((x,i)=>{ctx.strokeStyle=i===bird.lane?'#5feaff66':'#68a7d522';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()});ctx.restore();ctx.fillStyle='rgba(2,9,26,.12)';ctx.fillRect(0,0,W,H);obstacles.forEach(drawPillar);particles.forEach(p=>{ctx.globalAlpha=p.a;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.r*2,p.r*2)});ctx.globalAlpha=1;drawBird()}
function drawPillar(o){const top=o.y-o.gap/2,bottom=o.y+o.gap/2,w=o.w,g=ctx.createLinearGradient(o.x,0,o.x+w,0);g.addColorStop(0,'#061326');g.addColorStop(.45,'#174676');g.addColorStop(.7,'#07152e');g.addColorStop(1,'#020817');ctx.fillStyle=g;ctx.shadowColor='#16bfff';ctx.shadowBlur=12;roundRect(o.x,-25,w,top+25,13);ctx.fill();roundRect(o.x,bottom,w,H-bottom+25,13);ctx.fill();ctx.shadowColor='#f330ff';ctx.shadowBlur=18;ctx.fillStyle='#ec3bff';ctx.fillRect(o.x-7,top-13,w+14,13);ctx.fillRect(o.x-7,bottom,w+14,13);ctx.shadowBlur=0;if(o.coin&&!o.scored){ctx.save();ctx.translate(o.x+w/2,o.y);ctx.scale(.7+.18*Math.sin(o.phase),1);ctx.fillStyle='#ffd036';ctx.strokeStyle='#fff19a';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,20,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#9c6000';ctx.font='bold 18px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('$',0,1);ctx.restore()}}
function drawBird(){const size=Math.max(82,Math.min(118,H*.13));ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rot);ctx.shadowColor='#27ddff';ctx.shadowBlur=18;if(birdSprite.complete&&birdSprite.naturalWidth)ctx.drawImage(birdSprite,-size*.7,-size*.55,size*1.4,size*1.1);else{ctx.fillStyle='#1bb9f2';ctx.beginPath();ctx.arc(0,0,size*.28,0,7);ctx.fill()}ctx.restore()}

function progressFor(d){return Math.min(d.goal,+save.missions[d.key]||0)}
function resetText(){const n=new Date(),t=new Date(n);t.setHours(24,0,0,0);const ms=t-n;return`${Math.floor(ms/3600000)}h ${Math.floor(ms%3600000/60000)}m`}
const menus={
worlds:{title:'WORLD SELECT',html:()=>{const stars=save.bestByWorld.filter(Boolean).length*3;return`<div class="world-layout"><div class="world-cards">${worlds.map((w,i)=>{const locked=!worldUnlocked(i);return`<button class="world-card ${save.world===i?'selected':''} ${locked?'locked':''}" data-world="${i}" aria-pressed="${save.world===i}"><span class="world-number">${i+1}</span><span class="world-art ${w.css}"></span><b>${w.name}</b><small>${locked?`UNLOCK AT ${w.unlock.toLocaleString()}`:'BEST SCORE'}</small><em>${locked?'🔒':(save.bestByWorld[i]||0).toLocaleString()}</em></button>`}).join('')}</div><div class="total-progress"><b>TOTAL PROGRESS</b><span>⭐ ${stars} / 15</span><progress value="${stars}" max="15"></progress><button class="progress-reward" disabled>NEXT REWARD: 9 ⭐</button></div></div>`}},
characters:{title:'CHARACTER SELECT',html:()=>{const c=characters[save.bird];return`<div class="character-layout"><div class="character-stage"><div class="character-glow"></div><span class="character-art ${c.css}" style="background-image:url('${c.asset}')"></span></div><div class="character-info"><h2>${c.name}</h2><label>${c.rarity}</label>${[['Speed',c.speed],['Boost',c.boost],['Control',c.control]].map(([n,v])=>`<div class="stat ${n.toLowerCase()}"><b>${n}</b><i><span style="width:${v}%"></span></i><strong>${v}</strong></div>`).join('')}<button class="selected-button" disabled>SELECTED ✓</button></div><div class="character-strip">${characters.map((x,i)=>{const owned=save.ownedCharacters.includes(i);return`<button data-character="${i}" class="character-thumb ${save.bird===i?'selected':''} ${owned?'':'locked'}" aria-pressed="${save.bird===i}"><span class="character-art ${x.css}" style="background-image:url('${x.asset}')"></span><small>${owned?x.name:`🔒 ${x.name}`}</small></button>`}).join('')}</div></div>`}},
missions:{title:'MISSIONS',html:()=>`<div class="mission-shell"><div class="mission-tabs"><button class="active" data-mission-tab="daily">DAILY <i>${missionDefs.filter((d,i)=>progressFor(d)>=d.goal&&!save.missions.claimed.includes(i)).length}</i></button><button data-mission-tab="weekly">WEEKLY</button><span>◷ Resets in: ${resetText()}</span></div><div class="mission-list">${missionDefs.map((d,i)=>{const v=progressFor(d),complete=v>=d.goal,claimed=save.missions.claimed.includes(i);return`<div class="mission-row"><span class="mission-icon">${d.icon}</span><div><b>${d.label}</b><progress value="${v}" max="${d.goal}"></progress><small>${v.toLocaleString()} / ${d.goal.toLocaleString()}</small></div><strong>${d.type==='coins'?'🪙':'💎'} ${d.reward}</strong><button class="mission-go ${complete?'complete':''}" data-mission="${i}" ${claimed?'disabled':''}>${claimed?'CLAIMED':complete?'CLAIM':'GO'}</button></div>`}).join('')}</div><div class="mission-bonus">Complete all daily missions for the bonus <button data-bonus ${save.missions.claimed.length<missionDefs.length||save.missions.bonusClaimed?'disabled':''}>${save.missions.bonusClaimed?'CLAIMED':'🎁 +500'}</button></div></div>`},
shop:{title:'HANGAR SHOP',html:()=>{const visible=activeShopTab===0?shopItems.slice(0,4):shopItems.filter(x=>x.tab===activeShopTab);const exchanges=activeShopTab===0||activeShopTab===5;return`<div class="shop-shell"><nav class="shop-tabs">${['Featured','Characters','Skins','Trails','Power-ups','Coins & Gems'].map((x,i)=>`<button data-shop-tab="${i}" class="${i===activeShopTab?'active':''}">${['★','◆','✦','〰','⚡','◉'][i]} ${x}</button>`).join('')}</nav><div class="shop-content">${exchanges?`<div class="offer-row"><article class="offer-card"><i>-50%</i><h3>COIN VAULT</h3><span class="offer-art coin-chest"></span><b>2,000 🪙</b><button data-exchange="coins">💎 50</button></article><article class="offer-card"><i>BEST VALUE</i><h3>GEM CACHE</h3><span class="offer-art gem-chest"></span><b>100 💎</b><button data-exchange="gems">🪙 2,500</button></article></div>`:''}<h3>${activeShopTab===0?'FEATURED GEAR':['','CHARACTERS','SKINS','TRAILS','POWER-UPS','CURRENCY EXCHANGE'][activeShopTab]}</h3><div class="coin-packs">${visible.length?visible.map(x=>`<button data-buy="${x.id}" ${save.purchases.includes(x.id)?'disabled':''}><span>${x.icon}</span><b>${x.name}</b><small>${save.purchases.includes(x.id)?'OWNED':`${x.type==='coins'?'🪙':'💎'} ${x.cost}`}</small></button>`).join(''):'<div class="shop-empty">Choose an exchange offer above.</div>'}</div></div></div>`}},
leaderboard:{title:'LEADERBOARD',html:()=>`<div class="leaderboard-head"><span>SEASON 1</span><b>Your best: ${save.best.toLocaleString()}</b></div><div class="list leaderboard-list">${[['NovaPilot',45820],['SkyRider',38450],['PLAYER ONE',save.best],['ByteWing',22190],['CloudAce',18775]].sort((a,b)=>b[1]-a[1]).map((x,i)=>`<div class="row ${x[0]==='PLAYER ONE'?'you':''}"><b>#${i+1}</b><span class="grow">${x[0]}</span><b>${x[1].toLocaleString()}</b></div>`).join('')}</div>`},
settings:{title:'SETTINGS',html:()=>`<div class="settings-card panel">${[['music','Music','Menu ambience'],['sfx','Sound effects','Flaps, rewards and impacts'],['haptics','Haptics','Touch vibration feedback'],['hints','Control hints','Show gameplay guidance']].map(([k,l,d])=>`<div class="setting"><span><b>${l}</b><small>${d}</small></span><button class="setting-toggle ${save.settings[k]?'on':''}" data-setting="${k}" aria-pressed="${save.settings[k]}"><i></i><em>${save.settings[k]?'ON':'OFF'}</em></button></div>`).join('')}<button class="reset-progress" data-reset-progress>RESET LOCAL PROGRESS</button></div>`}};
function openMenu(name){const m=menus[name];if(!m)return;$('#panelTitle').textContent=m.title;$('#panelCurrency').innerHTML=['missions','settings','leaderboard'].includes(name)?'':`<span class="panel currency-pill">🪙 <b data-coins>${save.coins.toLocaleString()}</b></span><span class="panel currency-pill">💎 <b data-gems>${save.gems.toLocaleString()}</b></span>`;$('#panelContent').innerHTML=m.html();show('panelScreen');bindPanel()}
function bindPanel(){$$('[data-world]').forEach(b=>b.onclick=()=>{const i=+b.dataset.world;if(!worldUnlocked(i))return toast(`Reach ${worlds[i].unlock.toLocaleString()} points to unlock`);save.world=i;persist();openMenu('worlds');toast(`${worlds[i].name} selected`)});$$('[data-character]').forEach(b=>b.onclick=()=>{const i=+b.dataset.character;if(!save.ownedCharacters.includes(i)){activeShopTab=1;openMenu('shop');return toast(`Unlock ${characters[i].name} in the shop`)}save.bird=i;persist();openMenu('characters');toast(`${characters[save.bird].name} selected`)});$$('[data-mission]').forEach(b=>b.onclick=()=>{const i=+b.dataset.mission,d=missionDefs[i];if(progressFor(d)>=d.goal&&!save.missions.claimed.includes(i)){save.missions.claimed.push(i);save[d.type]+=d.reward;persist();openMenu('missions');toast('Reward claimed');sound(880,.12)}else start()});$('[data-bonus]')?.addEventListener('click',()=>{save.coins+=500;save.missions.bonusClaimed=true;persist();openMenu('missions');toast('Daily bonus claimed')});$$('[data-mission-tab]').forEach(b=>b.onclick=()=>b.dataset.missionTab==='weekly'?toast('Weekly missions unlock at Level 20'):openMenu('missions'));$$('[data-shop-tab]').forEach(b=>b.onclick=()=>{activeShopTab=+b.dataset.shopTab;openMenu('shop')});$$('[data-buy]').forEach(b=>b.onclick=()=>{const x=shopItems.find(i=>i.id===b.dataset.buy);if(save[x.type]<x.cost)return toast(`Not enough ${x.type}`);save[x.type]-=x.cost;save.purchases.push(x.id);if(Number.isInteger(x.character)&&!save.ownedCharacters.includes(x.character))save.ownedCharacters.push(x.character);persist();openMenu('shop');toast(`${x.name} purchased`)});$$('[data-exchange]').forEach(b=>b.onclick=()=>{if(b.dataset.exchange==='coins'){if(save.gems<50)return toast('Not enough gems');save.gems-=50;save.coins+=2000}else{if(save.coins<2500)return toast('Not enough coins');save.coins-=2500;save.gems+=100}persist();openMenu('shop');toast('Currency exchanged')});$$('[data-setting]').forEach(b=>b.onclick=()=>{const k=b.dataset.setting;save.settings[k]=!save.settings[k];persist();openMenu('settings');if(k==='music')applyMusic();toast(`${k} ${save.settings[k]?'enabled':'disabled'}`)});$('[data-reset-progress]')?.addEventListener('click',()=>{if(confirm('Reset all local progress?')){localStorage.removeItem('flapverse-save');location.reload()}})}
$$('[data-open]').forEach(b=>b.onclick=e=>{e.stopPropagation();openMenu(b.dataset.open)});$('.back').onclick=()=>show('home');$$('[data-home]').forEach(b=>b.onclick=()=>{running=false;cancelAnimationFrame(raf);show('home')});$('[data-daily]').onclick=()=>{const today=new Date().toISOString().slice(0,10);if(save.dailyClaimed===today)return toast('Daily reward already claimed');save.dailyClaimed=today;save.coins+=500;persist();updateHomeWorld();toast('Daily reward: 500 coins');haptic([30,50,30]);sound(920,.14)};$('#playBtn').onclick=start;$('#retryBtn').onclick=start;$('#adBtn').onclick=()=>{if($('#adBtn').disabled||$('#adBtn').classList.contains('claimed'))return;save.coins+=runCoins;persist();$('#rewardCoins').textContent=runCoins*2;$('#adBtn').disabled=true;$('#adBtn').classList.add('claimed');$('#adBtn').innerHTML='✓ REWARD DOUBLED';toast('Prototype ad reward granted')};$('#pauseBtn').onclick=()=>{if(!running)return;paused=true;$('#paused').classList.remove('hidden');haptic()};$('#resumeBtn').onclick=()=>{paused=false;last=performance.now();$('#paused').classList.add('hidden');haptic()};
homeVideo.addEventListener('loadeddata',()=>homeVideo.classList.add('ready'));homeVideo.addEventListener('waiting',()=>homeVideo.classList.remove('ready'));homeVideo.addEventListener('error',()=>{$('#home').classList.add('video-error');toast('Using static world background')});document.addEventListener('visibilitychange',()=>{if(document.hidden){homeVideo.pause();homeMusic.pause();if(running){paused=true;$('#paused').classList.remove('hidden')}}else if(state==='home')updateHomeWorld()});persist();updateHomeWorld();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
